### ISSUE TITLE
[feature request] dark mode switcher

### ISSUE THREAD

**Issue by mykiwi** [Halleck45/ast-metrics#52]
Hi,
Some elements are difficult to read and I think it is because of the dark mode.
Maybe a button to switch it could be a first step to improve it?

Example:
![Screenshot 2024-04-28 at 11-57-33 AST Metrics - Overview](https://github.com/Halleck45/ast-metrics/assets/334432/32e81cc1-46bc-4a69-b5ba-b1d57a66aaa2)

**Comment by Halleck45** [comment]
Hi @mykiwi,

thanks for the report ! 

Indeed, I hadn't noticed.

It's relatively easy to fix, are you interested? It's HTML in the file [`src/Report/Html/templates/index.html`](https://github.com/Halleck45/ast-metrics/blob/main/src/Report/Html/templates/index.html). Would you be interested in opening a PR ?
